package com.eobme.app.ui.screens.appeal

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.Save
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import com.eobme.app.EOBmeApp
import com.eobme.app.R
import com.eobme.app.util.DateUtils
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AppealLetterScreen(
    eobId: Long,
    app: EOBmeApp,
    onBack: () -> Unit
) {
    val eob by app.eobRepository.observeEob(eobId).collectAsState(initial = null)
    val userId by app.userPreferences.userId.collectAsState(initial = -1L)
    val user by app.userRepository.observeUser(userId).collectAsState(initial = null)
    var letterText by remember { mutableStateOf("") }
    var isEditing by remember { mutableStateOf(false) }
    var isGenerated by remember { mutableStateOf(false) }

    LaunchedEffect(eob, user) {
        val e = eob ?: return@LaunchedEffect
        val u = user ?: return@LaunchedEffect
        if (!isGenerated) {
            letterText = generateAppealLetter(
                userName = "${u.firstName} ${u.lastName}",
                userCity = u.city,
                userState = u.state,
                userEmail = u.email,
                subscriberId = u.subscriberId.ifBlank { e.rawOcrText.let { "" } },
                insuranceName = e.insuranceName,
                providerName = e.providerName,
                dateOfService = DateUtils.formatDate(e.dateOfService),
                billedAmount = e.billedAmount,
                insurancePaid = e.insurancePaid
            )
            isGenerated = true
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.appeal_letter)) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = stringResource(R.string.back))
                    }
                },
                actions = {
                    IconButton(onClick = { isEditing = !isEditing }) {
                        Icon(
                            if (isEditing) Icons.Default.Save else Icons.Default.Edit,
                            contentDescription = stringResource(R.string.edit)
                        )
                    }
                }
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp)
                .verticalScroll(rememberScrollState())
        ) {
            if (isEditing) {
                OutlinedTextField(
                    value = letterText,
                    onValueChange = { letterText = it },
                    modifier = Modifier
                        .fillMaxWidth()
                        .weight(1f, fill = false),
                    textStyle = MaterialTheme.typography.bodyMedium,
                    minLines = 20
                )
            } else {
                Text(
                    text = letterText.ifBlank { stringResource(R.string.generating_letter) },
                    style = MaterialTheme.typography.bodyMedium
                )
            }
        }
    }
}

private fun generateAppealLetter(
    userName: String,
    userCity: String,
    userState: String,
    userEmail: String,
    subscriberId: String,
    insuranceName: String,
    providerName: String,
    dateOfService: String,
    billedAmount: Double,
    insurancePaid: Double
): String {
    val today = SimpleDateFormat("MMMM dd, yyyy", Locale.US).format(Date())
    val location = listOf(userCity, userState).filter { it.isNotBlank() }.joinToString(", ")

    return buildString {
        appendLine(userName)
        if (location.isNotBlank()) appendLine(location)
        if (userEmail.isNotBlank()) appendLine(userEmail)
        appendLine()
        appendLine(today)
        appendLine()
        if (insuranceName.isNotBlank()) {
            appendLine(insuranceName)
            appendLine("Appeals Department")
        } else {
            appendLine("[Insurance Company Name]")
            appendLine("Appeals Department")
        }
        appendLine("[Insurance Company Address]")
        appendLine()
        appendLine("RE: Appeal of Claim Denial / Payment Discrepancy")
        if (subscriberId.isNotBlank()) appendLine("Member ID: $subscriberId")
        appendLine("Date of Service: $dateOfService")
        if (providerName.isNotBlank()) appendLine("Provider: $providerName")
        appendLine()
        appendLine("Dear Appeals Department,")
        appendLine()
        appendLine("I am writing to formally appeal the processing of my claim for services rendered on $dateOfService" +
                if (providerName.isNotBlank()) " by $providerName." else ".")
        appendLine()
        if (billedAmount > 0.0) {
            appendLine("The total billed amount for this service was $${String.format("%.2f", billedAmount)}.")
        }
        if (insurancePaid > 0.0) {
            appendLine("The plan paid $${String.format("%.2f", insurancePaid)} toward this claim.")
        }
        if (billedAmount > 0.0 && insurancePaid > 0.0 && billedAmount > insurancePaid) {
            val difference = billedAmount - insurancePaid
            appendLine("This leaves a remaining balance of $${String.format("%.2f", difference)} that I believe should be covered under my plan benefits.")
        }
        appendLine()
        appendLine("I believe this claim was not processed correctly for the following reasons:")
        appendLine()
        appendLine("1. The services provided were medically necessary as determined by my treating physician.")
        appendLine("2. These services are covered under my current plan benefits.")
        appendLine("3. [Please add any additional specific reasons for your appeal here.]")
        appendLine()
        appendLine("I respectfully request that you review this claim and reprocess it accordingly. Enclosed, please find supporting documentation, including the Explanation of Benefits and any relevant medical records.")
        appendLine()
        appendLine("Please contact me at $userEmail if you require additional information. I look forward to your prompt resolution of this matter.")
        appendLine()
        appendLine("Sincerely,")
        appendLine(userName)
    }
}
