# =============================================================================
# EOBme — minimal R8 release rules
# Shield all local application code; allow third-party library tree-shaking only.
# =============================================================================

# Absolute architecture protection — entire custom package is excluded from R8.
-keep class app.eob.me.** { *; }

# Preserve annotations and generics used by Gson, Retrofit, and Crashlytics mapping.
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes InnerClasses
-keepattributes EnclosingMethod
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Kotlin metadata required for reflection and coroutines.
-keep class kotlin.Metadata { *; }
-dontwarn kotlin.**
-dontwarn kotlinx.coroutines.**

# Gson field names for any serialized models (Veryfi/Firebase DTOs live under app.eob.me).
-keepclassmembers,allowobfuscation class * {
    @com.google.gson.annotations.SerializedName <fields>;
}

# Retrofit / OkHttp — suppress benign third-party warnings during shrinking.
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn retrofit2.**
-keep,allowobfuscation,allowshrinking interface retrofit2.Call
-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation

# Coil image loading.
-dontwarn coil.**

# Firebase / Google Play Services consumer SDK warnings.
-dontwarn com.google.firebase.**
-dontwarn com.google.android.gms.**

# RevenueCat / Play Billing.
-dontwarn com.revenuecat.purchases.**
-dontwarn com.android.billingclient.**

# CameraX / ML Kit.
-dontwarn androidx.camera.**
-dontwarn com.google.mlkit.**

# Jetpack Compose compiler/runtime.
-dontwarn androidx.compose.**

# WorkManager Room implementation (generated by androidx.work).
-keep class * extends androidx.work.Worker
-keep class * extends androidx.work.ListenableWorker
-keep class androidx.work.impl.** { *; }
-dontwarn androidx.work.**
