package com.eobme.app.reference

object InsuranceCompanies {

    data class InsuranceInfo(
        val name: String,
        val aliases: List<String> = emptyList()
    )

    val all: List<InsuranceInfo> = listOf(
        InsuranceInfo("Aetna", listOf("AETNA", "Aetna Inc", "Aetna Health")),
        InsuranceInfo("Anthem", listOf("ANTHEM", "Anthem Blue Cross", "Anthem BCBS", "Anthem Inc")),
        InsuranceInfo("Blue Cross Blue Shield", listOf("BCBS", "Blue Cross", "Blue Shield", "BlueCross BlueShield", "Blue Cross BlueShield", "BLUE CROSS BLUE SHIELD")),
        InsuranceInfo("Blue Cross Blue Shield of Alabama", listOf("BCBS Alabama", "BCBSAL")),
        InsuranceInfo("Blue Cross Blue Shield of Arizona", listOf("BCBS Arizona", "BCBSAZ")),
        InsuranceInfo("Blue Cross Blue Shield of Florida", listOf("Florida Blue", "BCBS Florida")),
        InsuranceInfo("Blue Cross Blue Shield of Georgia", listOf("BCBS Georgia")),
        InsuranceInfo("Blue Cross Blue Shield of Illinois", listOf("BCBS Illinois", "BCBSIL")),
        InsuranceInfo("Blue Cross Blue Shield of Louisiana", listOf("BCBS Louisiana")),
        InsuranceInfo("Blue Cross Blue Shield of Massachusetts", listOf("BCBS Massachusetts", "BCBSMA")),
        InsuranceInfo("Blue Cross Blue Shield of Michigan", listOf("BCBS Michigan", "BCBSM")),
        InsuranceInfo("Blue Cross Blue Shield of Minnesota", listOf("BCBS Minnesota")),
        InsuranceInfo("Blue Cross Blue Shield of New Jersey", listOf("Horizon BCBS", "Horizon Blue Cross")),
        InsuranceInfo("Blue Cross Blue Shield of North Carolina", listOf("BCBS NC", "Blue Cross NC")),
        InsuranceInfo("Blue Cross Blue Shield of South Carolina", listOf("BCBS SC")),
        InsuranceInfo("Blue Cross Blue Shield of Tennessee", listOf("BCBS Tennessee", "BCBST")),
        InsuranceInfo("Blue Cross Blue Shield of Texas", listOf("BCBS Texas", "BCBSTX")),
        InsuranceInfo("CareFirst BlueCross BlueShield", listOf("CareFirst", "CareFirst BCBS")),
        InsuranceInfo("Cigna", listOf("CIGNA", "Cigna Healthcare", "Cigna Health", "The Cigna Group")),
        InsuranceInfo("UnitedHealthcare", listOf("United Healthcare", "UHC", "UNITED HEALTHCARE", "United Health Care", "UnitedHealth", "United Health Group")),
        InsuranceInfo("Humana", listOf("HUMANA", "Humana Inc", "Humana Health")),
        InsuranceInfo("Kaiser Permanente", listOf("KAISER", "Kaiser", "Kaiser Foundation")),
        InsuranceInfo("Molina Healthcare", listOf("MOLINA", "Molina")),
        InsuranceInfo("Centene", listOf("CENTENE", "Centene Corporation")),
        InsuranceInfo("WellCare", listOf("WELLCARE", "WellCare Health Plans")),
        InsuranceInfo("Ambetter", listOf("AMBETTER", "Ambetter Health")),
        InsuranceInfo("Oscar Health", listOf("OSCAR", "Oscar")),
        InsuranceInfo("Clover Health", listOf("CLOVER", "Clover")),
        InsuranceInfo("Bright Health", listOf("BRIGHT HEALTH")),
        InsuranceInfo("Devoted Health", listOf("DEVOTED")),
        InsuranceInfo("Friday Health Plans", listOf("FRIDAY")),
        InsuranceInfo("Alignment Healthcare", listOf("ALIGNMENT")),
        InsuranceInfo("Health Net", listOf("HEALTH NET", "HealthNet")),
        InsuranceInfo("Medical Mutual", listOf("MEDICAL MUTUAL")),
        InsuranceInfo("Priority Health", listOf("PRIORITY HEALTH")),
        InsuranceInfo("EmblemHealth", listOf("EMBLEMHEALTH", "Emblem Health", "GHI", "HIP")),
        InsuranceInfo("Highmark", listOf("HIGHMARK", "Highmark BCBS")),
        InsuranceInfo("Independence Blue Cross", listOf("IBX", "Independence BC")),
        InsuranceInfo("Regence", listOf("REGENCE", "Regence BCBS")),
        InsuranceInfo("Premera Blue Cross", listOf("PREMERA", "Premera")),
        InsuranceInfo("Excellus BlueCross BlueShield", listOf("EXCELLUS", "Excellus BCBS")),
        InsuranceInfo("Capital BlueCross", listOf("CAPITAL BLUECROSS")),
        InsuranceInfo("Harvard Pilgrim Health Care", listOf("HARVARD PILGRIM")),
        InsuranceInfo("Tufts Health Plan", listOf("TUFTS")),
        InsuranceInfo("ConnectiCare", listOf("CONNECTICARE")),
        InsuranceInfo("MVP Health Care", listOf("MVP")),
        InsuranceInfo("UPMC Health Plan", listOf("UPMC")),
        InsuranceInfo("Geisinger Health Plan", listOf("GEISINGER")),
        InsuranceInfo("SelectHealth", listOf("SELECTHEALTH")),
        InsuranceInfo("Sanford Health Plan", listOf("SANFORD")),
        InsuranceInfo("Medica", listOf("MEDICA")),
        InsuranceInfo("PreferredOne", listOf("PREFERREDONE")),
        InsuranceInfo("HealthPartners", listOf("HEALTHPARTNERS", "Health Partners")),
        InsuranceInfo("Quartz", listOf("QUARTZ")),
        InsuranceInfo("Dean Health Plan", listOf("DEAN")),
        InsuranceInfo("Security Health Plan", listOf("SECURITY HEALTH")),
        InsuranceInfo("Physicians Health Plan", listOf("PHP")),
        InsuranceInfo("HAP (Health Alliance Plan)", listOf("HAP")),
        InsuranceInfo("McLaren Health Plan", listOf("MCLAREN")),
        InsuranceInfo("Meridian Health Plan", listOf("MERIDIAN")),
        InsuranceInfo("SilverSummit Health Plan", listOf("SILVERSUMMIT")),
        InsuranceInfo("Peach State Health Plan", listOf("PEACH STATE")),
        InsuranceInfo("Sunshine Health", listOf("SUNSHINE HEALTH")),
        InsuranceInfo("Absolute Total Care", listOf("ABSOLUTE TOTAL CARE")),
        InsuranceInfo("Amerigroup", listOf("AMERIGROUP")),
        InsuranceInfo("CareSource", listOf("CARESOURCE")),
        InsuranceInfo("Community Health Plan", listOf("COMMUNITY HEALTH PLAN")),
        InsuranceInfo("Fidelis Care", listOf("FIDELIS")),
        InsuranceInfo("Healthfirst", listOf("HEALTHFIRST")),
        InsuranceInfo("LA Care Health Plan", listOf("LA CARE", "L.A. Care")),
        InsuranceInfo("MetroPlus Health Plan", listOf("METROPLUS")),
        InsuranceInfo("CalOptima", listOf("CALOPTIMA")),
        InsuranceInfo("Partnership HealthPlan", listOf("PARTNERSHIP HEALTHPLAN")),
        InsuranceInfo("Inland Empire Health Plan", listOf("IEHP")),
        InsuranceInfo("San Francisco Health Plan", listOf("SFHP")),
        InsuranceInfo("Santa Clara Family Health Plan", listOf("SCFHP")),
        InsuranceInfo("TRICARE", listOf("Tricare", "TRI-CARE", "Tricare Prime", "Tricare Select", "Tricare for Life")),
        InsuranceInfo("Medicare", listOf("MEDICARE", "Medicare Part A", "Medicare Part B", "Medicare Advantage")),
        InsuranceInfo("Medicaid", listOf("MEDICAID")),
        InsuranceInfo("Veterans Affairs (VA)", listOf("VA", "Veterans Affairs", "VA Health")),
        InsuranceInfo("CHAMPVA", listOf("CHAMP VA")),
        InsuranceInfo("Aflac", listOf("AFLAC")),
        InsuranceInfo("MetLife", listOf("METLIFE", "Metropolitan Life")),
        InsuranceInfo("Guardian Life", listOf("GUARDIAN", "Guardian")),
        InsuranceInfo("Lincoln Financial", listOf("LINCOLN FINANCIAL", "Lincoln National")),
        InsuranceInfo("Principal Financial", listOf("PRINCIPAL")),
        InsuranceInfo("Sun Life", listOf("SUN LIFE", "Sun Life Financial")),
        InsuranceInfo("Unum", listOf("UNUM")),
        InsuranceInfo("Hartford", listOf("THE HARTFORD", "Hartford")),
        InsuranceInfo("Zurich", listOf("ZURICH")),
        InsuranceInfo("Travelers", listOf("TRAVELERS")),
        InsuranceInfo("State Farm", listOf("STATE FARM")),
        InsuranceInfo("Allstate", listOf("ALLSTATE")),
        InsuranceInfo("Progressive", listOf("PROGRESSIVE")),
        InsuranceInfo("GEICO", listOf("Geico")),
        InsuranceInfo("Nationwide", listOf("NATIONWIDE")),
        InsuranceInfo("Liberty Mutual", listOf("LIBERTY MUTUAL")),
        InsuranceInfo("Workers Compensation", listOf("WORKERS COMP", "Work Comp", "WC")),
        InsuranceInfo("Coventry Health Care", listOf("COVENTRY")),
        InsuranceInfo("AvMed", listOf("AVMED")),
        InsuranceInfo("Capital Health Plan", listOf("CAPITAL HEALTH")),
        InsuranceInfo("HealthSpring", listOf("HEALTHSPRING")),
        InsuranceInfo("WellPoint", listOf("WELLPOINT")),
        InsuranceInfo("Group Health Cooperative", listOf("GROUP HEALTH")),
        InsuranceInfo("CDPHP", listOf("Capital District Physicians Health Plan")),
        InsuranceInfo("Fallon Health", listOf("FALLON")),
        InsuranceInfo("Point32Health", listOf("POINT32HEALTH")),
        InsuranceInfo("Sentara Health Plans", listOf("SENTARA")),
        InsuranceInfo("Virginia Premier", listOf("VIRGINIA PREMIER")),
        InsuranceInfo("Optima Health", listOf("OPTIMA")),
        InsuranceInfo("Carilion Health Plans", listOf("CARILION")),
        InsuranceInfo("Johns Hopkins Health Plans", listOf("JOHNS HOPKINS")),
        InsuranceInfo("Cambia Health Solutions", listOf("CAMBIA")),
        InsuranceInfo("Moda Health", listOf("MODA")),
        InsuranceInfo("Providence Health Plan", listOf("PROVIDENCE")),
        InsuranceInfo("PacificSource Health Plans", listOf("PACIFICSOURCE")),
        InsuranceInfo("Deseret Mutual", listOf("DESERET MUTUAL")),
        InsuranceInfo("AARP", listOf("AARP Health")),
        InsuranceInfo("Sutter Health Plus", listOf("SUTTER HEALTH")),
        InsuranceInfo("Sharp Health Plan", listOf("SHARP")),
        InsuranceInfo("Western Health Advantage", listOf("WESTERN HEALTH")),
        InsuranceInfo("Chinese Community Health Plan", listOf("CCHP"))
    )

    fun matchInsuranceName(ocrText: String): String {
        val upper = ocrText.uppercase()
        for (insurance in all) {
            if (upper.contains(insurance.name.uppercase())) return insurance.name
            for (alias in insurance.aliases) {
                if (upper.contains(alias.uppercase())) return insurance.name
            }
        }
        return ""
    }
}
